### ISSUE TITLE
KafkaConsumerActor fails to re-subscribe once restarted due to an exception

### ISSUE THREAD

**Issue by bezchristo** [alexvaluyskiy/Akka.Streams.Kafka#323]
**Version Information**
Akka.Streams.Kafka 1.2.1

**Describe the bug**
When an "Unexpected records polled" exception gets raised in the [KafkaConsumerActor](https://github.com/akkadotnet/Akka.Streams.Kafka/blob/2759b65b45b52ce0aeb62d2e71d5def8204db040/src/Akka.Streams.Kafka/Stages/Consumers/Actors/KafkaConsumerActor.cs#L592) the Actor gets restarted but after the restart all subsequent Polls return null when  [_consumer.Consume(timeout)](https://github.com/akkadotnet/Akka.Streams.Kafka/blob/2759b65b45b52ce0aeb62d2e71d5def8204db040/src/Akka.Streams.Kafka/Stages/Consumers/Actors/KafkaConsumerActor.cs#L569) is called.

Since the KafkaConsumerActor gets restarted due to default supervision with the exception being thrown and not recreated via [BaseSingleSourceLogic](https://github.com/akkadotnet/Akka.Streams.Kafka/blob/2759b65b45b52ce0aeb62d2e71d5def8204db040/src/Akka.Streams.Kafka/Stages/Consumers/Abstract/BaseSingleSourceLogic.cs#L71) it never calls `ConfigureSubscription` after it's recreated. Which means the consumer gets created but never subscribes properly.

**To Reproduce**
1. Throw and exception in KafkaConsumerActor which does not get handled.
2. The actor will restart and will fail to consume any further messages

**Expected behavior**
When an "Unexpected records polled" exception is thrown the actor should be stopped and a failure message should be sent, which the logic in [BaseSingleSourceLogic](https://github.com/akkadotnet/Akka.Streams.Kafka/blob/2759b65b45b52ce0aeb62d2e71d5def8204db040/src/Akka.Streams.Kafka/Stages/Consumers/Abstract/BaseSingleSourceLogic.cs#L132) will then handle. Depending on the Decider the KafkaConsumerActor will then either be recreated or left as terminated. Letting the actor get recreated via BaseSingleSourceLogic will ensure that the consumer also resubscribes after creation.

**Actual behavior**
An exception is thrown and the default supervision just restarts the consumer actor without subscribing for events.

**Environment**
Windows, .NET 6

**Comment by bezchristo** [comment]
I am in the process of creating a PR for this.

**Comment by Aaronontheweb** [comment]
Thanks @bezchristo - based on our discussion in Discord this sounds right to me.

**Comment by Aaronontheweb** [comment]
closed via https://github.com/akkadotnet/Akka.Streams.Kafka/pull/324
